---
title: "breakout"
author: "Levi Knigge"
date: "17-2-2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r cars}
library(tidyverse)
library(spotifyr)
library(compmus)
library(gridExtra)
```

## Including Plots


```{r}
vulfpeck <- get_playlist_audio_features("", "3nI3zFZc0zNawgGGBvlLjd")
woody <- get_playlist_audio_features("", "1YNoeB7YRKmwXDwxL6kXHv")
corywong <- get_playlist_audio_features("", "6PTxkUtHVL2MVwBVw45HhC")
katzman <- get_playlist_audio_features("", "26kcyNqQKAN3fnuO8NCL4B")

# summary(vulfpeck)

artists <-
  bind_rows(
    vulfpeck %>% mutate(category = "Vulfpeck"),
    woody %>% mutate(category = "Woody"),
    corywong %>% mutate(category = "Cory Wong"),
    katzman %>% mutate(category = "Katzman")
  )

wood <-
  get_tidy_audio_analysis("2IB1LWbNli57u0k7U1GAXt") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)
```
```{r}
wood %>%
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) %>%
  compmus_gather_chroma() %>% 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c() +
  xlim(15, 25)


wood %>%
  mutate(pitches = map(pitches, compmus_normalise, "manhattan")) %>%
  compmus_gather_chroma() %>% 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c() +
  xlim(15, 25)


wood %>%
  mutate(pitches = map(pitches, compmus_normalise, "chebyshev")) %>%
  compmus_gather_chroma() %>% 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c() + 
  xlim(15, 25)

```

```{r}
## The Tallis Scholars
tallis <-
  get_tidy_audio_analysis("2J3Mmybwue0jyQ0UVMYurH") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)
## La Chapelle Royale
chapelle <-
  get_tidy_audio_analysis("4ccw2IcnFt1Jv9LqQCOYDi") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)
## The Cambridge Singers
cambridge <-
  get_tidy_audio_analysis("54cAT1TCFaZbLOB2i1y61h") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)


## Oxford Camerata
oxford <-
  get_tidy_audio_analysis("5QyUsMY40MQ1VebZXSaonU") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)
## Chanticleer
chanticleer <-
  get_tidy_audio_analysis("1bocG1N8LM7MSgj9T1n3XH") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)


## The Hilliard Ensemble
hilliard <-
  get_tidy_audio_analysis("2rXEyq50luqaFNC9DkcU6k") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)
## The Gabrieli Consort
gabrieli <-
  get_tidy_audio_analysis("4NnJ4Jes8a8mQUfXhwuITx") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)

compmus_long_distance(
  gabrieli %>% mutate(pitches = map(pitches, compmus_normalise, "manhattan")),
  chapelle %>% mutate(pitches = map(pitches, compmus_normalise, "manhattan")),
  feature = pitches,
  method = "aitchison"
) %>%
  ggplot(
    aes(
      x = xstart + xduration / 2,
      width = xduration,
      y = ystart + yduration / 2,
      height = yduration,
      fill = d
    )
  ) +
  geom_tile() +
  coord_equal() +
  labs(x = "The Gabrielli Consort", y = "La Chapelle Royale") +
  theme_minimal() +
  scale_fill_viridis_c(guide = NULL)
```