---
title: "breakout4"
author: "Levi Knigge"
date: "10-3-2021"
output: html_document
---
#  cache = TRUE,
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(spotifyr)
library(gridExtra)
library(flexdashboard)
library(readr)
library(leaflet)
library(DT)
library(lubridate)
library(plotly)
library(gridExtra)
library(grid)
library(ggplot2)
library(lattice)
library(compmus)

```
```{r}
pata_pata <-
  get_tidy_audio_analysis("0vOAN45nUNSqRIWPTOSDsJ") %>%
  select(segments) %>%
  unnest(segments)
```

```{r}
pata_pata %>%
  mutate(loudness_max_time = start + loudness_max_time) %>%
  arrange(loudness_max_time) %>%
  mutate(delta_loudness = loudness_max - lag(loudness_max)) %>%
  ggplot(aes(x = loudness_max_time, y = pmax(0, delta_loudness))) +
  geom_line() +
  xlim(0, 30) +
  theme_minimal() +
  labs(x = "Time (s)", y = "Novelty")
```

```{r}
pata_pata %>%
  mutate(pitches = map(pitches, compmus_normalise, "clr")) %>%
  arrange(start) %>%
  mutate(pitches = map2(pitches, lag(pitches), `-`)) %>%
  slice(-1) %>%
  compmus_gather_chroma() %>%
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = pmax(0, value)
    )
  ) +
  geom_tile() +
  scale_fill_viridis_c(guide = "none") +
  xlim(0, 30) +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_classic()
```

```{r}
pata_pata %>%
  arrange(start) %>%
  mutate(timbre = map2(timbre, lag(timbre), `-`)) %>%
  slice(-1) %>%
  compmus_gather_timbre() %>%
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = basis,
      fill = pmax(0, value)
    )
  ) +
  geom_tile() +
  scale_fill_viridis_c(guide = "none") +
  xlim(0, 30) +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_classic()
```

```{r}
graveola <- get_tidy_audio_analysis("2WbKDH7BbDUHqACsZH0KVW")

graveola %>%
  tempogram(window_size = 8, hop_size = 1, cyclic = FALSE) %>%
  ggplot(aes(x = time, y = bpm, fill = power)) +
  geom_raster() +
  scale_fill_viridis_c(guide = "none") +
  labs(x = "Time (s)", y = "Tempo (BPM)") +
  theme_classic()

```
```{r}
graveola %>%
  tempogram(window_size = 8, hop_size = 1, cyclic = TRUE) %>%
  ggplot(aes(x = time, y = bpm, fill = power)) +
  geom_raster() +
  scale_fill_viridis_c(guide = "none") +
  labs(x = "Time (s)", y = "Tempo (BPM)") +
  theme_classic()
```

```{r}
graveola <- get_tidy_audio_analysis("2zI4fwCxbLbUY6QBdVjHOn")

graveola %>%
  tempogram(window_size = 8, hop_size = 1, cyclic = FALSE) %>%
  ggplot(aes(x = time, y = bpm, fill = power)) +
  geom_raster() +
  scale_fill_viridis_c(guide = "none") +
  labs(x = "Time (s)", y = "Tempo (BPM)") +
  theme_classic()

```

```{r}
graveola <- get_tidy_audio_analysis("0vOAN45nUNSqRIWPTOSDsJ")

graveola %>%
  tempogram(window_size = 8, hop_size = 1, cyclic = FALSE) %>%
  ggplot(aes(x = time, y = bpm, fill = power)) +
  geom_raster() +
  scale_fill_viridis_c(guide = "none") +
  labs(x = "Time (s)", y = "Tempo (BPM)") +
  theme_classic()

```